In [16]:
import numpy as np

## **BASICS**

In [17]:
a = np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [18]:
a.shape

(3, 5)

In [19]:
a.ndim

2

In [20]:
a.dtype

dtype('int64')

In [21]:
a.dtype.name

'int64'

In [22]:
a.size

15

In [23]:
type(a)

numpy.ndarray

In [24]:
b = np.array([6,7,8,9], dtype=complex)          ## b = np.array((6,7,8,9), dtype=complex)     
print(b)

[6.+0.j 7.+0.j 8.+0.j 9.+0.j]


In [25]:
b.reshape(2,2)

array([[6.+0.j, 7.+0.j],
       [8.+0.j, 9.+0.j]])

Original shape of b doesn't change on reshape.

In [26]:
print(b)

[6.+0.j 7.+0.j 8.+0.j 9.+0.j]


In [27]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.ones( (2,3,5), dtype=np.int16)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int16)

In [29]:
np.empty( (2,5), dtype=np.int8)

array([[ 16, -73,  46,   2,   0],
       [  0,   0,   0,   0,   0]], dtype=int8)

In [30]:
np.arange(10, 30)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [31]:
np.arange(10, 30, 3)

array([10, 13, 16, 19, 22, 25, 28])

-> np.arange **does not work with floating point** numbers due to precision problem.
Hence, **np.linspace** is used for floating points.
#### ## np.linspace( Initial, Final, no. of elements in bw)

In [32]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [34]:
d = np.arange(15).reshape((3,5))
print(d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [35]:
e = np.zeros_like(d)
print(e)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


Like zeros_like, ones_like and empty_like work same for 1, and garbage.

In [36]:
f = np.full((5, 4, 1), 6)
print(f)

[[[6]
  [6]
  [6]
  [6]]

 [[6]
  [6]
  [6]
  [6]]

 [[6]
  [6]
  [6]
  [6]]

 [[6]
  [6]
  [6]
  [6]]

 [[6]
  [6]
  [6]
  [6]]]


In [38]:
g = [1,2,3]
h = [3,2,3]

print(np.equal(g,h))
print(np.array_equal(g,h))

[False  True  True]
False


In [37]:
i = np.arange(13, 26)
print(i)

[13 14 15 16 17 18 19 20 21 22 23 24 25]
