In [ ]:
import numpy as np

## COPIES AND VIEWS

In [ ]:
a = np.arange(12)
b = a                              ## NO new object is created

In [ ]:
b

In [ ]:
b is a                            ## a & b are two names for same ndarray object

In [7]:
b.resize((3,4))         ## changes shape of a as well.
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
id(a)                ## id is a unique identifier of an object

140579181602576

In [10]:
id(b)

140579181602576

## VIEW OR SHALLOW COPY

In [11]:
c = a.view()
c is a

False

In [12]:
c.base is a        ## c is a view of the data owned by a

True

In [15]:
c.shape = 2,6
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [18]:
a.shape

(3, 4)

In [21]:
c[0,1] = 1234
c

array([[   0, 1234,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10,   11]])

In [20]:
a

array([[   0, 1234,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11]])

## DEEP COPY

In [22]:
d = a.copy()

In [23]:
d is a

False

In [24]:
d.base is a

False

In [26]:
d[0,0] = 99

In [27]:
a

array([[   0, 1234,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11]])