In [1]:
import numpy as np

## INDEXING, SLICING, ITERATING

In [2]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [3]:
a[2]

8

In [46]:
a[2:5]

array([ 8, 27, 64])

In [4]:
a[0:6:2]                      ## a[: 6: 2]

array([ 0,  8, 64])

In [5]:
a[:-2]

array([  0,   1,   8,  27,  64, 125, 216, 343])

In [6]:
a[: : -1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [7]:
a[: :2] = -1000
a 

array([-1000,     1, -1000,    27, -1000,   125, -1000,   343, -1000,
         729])

In [8]:
b = slice(2,7,2)
a[b]                            ## b = a[2:7:2]

array([-1000, -1000, -1000])

In [9]:
a[-1]

729

In [10]:
def f(x,y):
    return 10*x+y
b = np.fromfunction(f, (5,4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [11]:
print(b[0])
print(b[:2])

[0 1 2 3]
[[ 0  1  2  3]
 [10 11 12 13]]


In [12]:
b[2][3]    ## b[2,3]

23

In [13]:
b[0:5:2, 3]

array([ 3, 23, 43])

In [14]:
b[3, 0:5:2]

array([30, 32])

In [15]:
b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [16]:
b[-1, :]

array([40, 41, 42, 43])

In [17]:
b[:, 1]

array([ 1, 11, 21, 31, 41])

In [18]:
b[1,...]         ## b[1: :]

array([10, 11, 12, 13])

In [19]:
b[..., 2]

array([ 2, 12, 22, 32, 42])

## SHAPE MANIPULATION

In [20]:
a = np.floor(10*np.random.random((3,4)))
a

array([[2., 0., 7., 7.],
       [1., 5., 8., 1.],
       [3., 9., 3., 5.]])

In [21]:
a.shape

(3, 4)

In [22]:
a.size

12

In [23]:
a.ndim

2

In [24]:
## These functions do not modify the original array.

In [25]:
a.ravel()

array([2., 0., 7., 7., 1., 5., 8., 1., 3., 9., 3., 5.])

In [26]:
a.reshape((6,2))

array([[2., 0.],
       [7., 7.],
       [1., 5.],
       [8., 1.],
       [3., 9.],
       [3., 5.]])

In [27]:
a.T               ## TRANSPORTED ARRAY

array([[2., 1., 3.],
       [0., 5., 9.],
       [7., 8., 3.],
       [7., 1., 5.]])

In [28]:
a.shape

(3, 4)

In [29]:
## reshape() do not modify the original array but resize() modify the original array

In [30]:
a
a.shape

(3, 4)

In [31]:
a.resize((6,2))
a

array([[2., 0.],
       [7., 7.],
       [1., 5.],
       [8., 1.],
       [3., 9.],
       [3., 5.]])

In [32]:
## If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:

In [33]:
a.reshape(4,-1)

array([[2., 0., 7.],
       [7., 1., 5.],
       [8., 1., 3.],
       [9., 3., 5.]])

## STACKING TOGETHER TWO DIFFERENT ARRAYS

In [34]:
a = np.floor(10*np.random.random((2,2)))
a

array([[3., 0.],
       [8., 9.]])

In [35]:
b = np.floor(10*np.random.random((2,2)))
b

array([[0., 0.],
       [2., 4.]])

In [36]:
np.hstack((a,b))

array([[3., 0., 0., 0.],
       [8., 9., 2., 4.]])

In [73]:
np.vstack((a,b,a,b))

array([[3., 0.],
       [8., 9.],
       [0., 0.],
       [2., 4.],
       [3., 0.],
       [8., 9.],
       [0., 0.],
       [2., 4.]])

In [38]:
##T he function column_stack stacks 1D arrays as columns into a 2D array
## It is equivalent to hstack only for 2D arrays

In [39]:
np.column_stack((a,b))

array([[3., 0., 0., 0.],
       [8., 9., 2., 4.]])

In [40]:
np.row_stack((a,b))

array([[3., 0.],
       [8., 9.],
       [0., 0.],
       [2., 4.]])

## SPLITTING ONE ARRAY INTO SEVERAL SIMILAR ONES

In [70]:
x = np.floor(10*np.random.random((2,12)))
print(x)

[[8. 6. 6. 1. 3. 4. 7. 9. 2. 9. 0. 4.]
 [5. 4. 7. 7. 1. 3. 0. 9. 0. 2. 0. 9.]]


In [71]:
np.hsplit(x,3)

[array([[8., 6., 6., 1.],
        [5., 4., 7., 7.]]), array([[3., 4., 7., 9.],
        [1., 3., 0., 9.]]), array([[2., 9., 0., 4.],
        [0., 2., 0., 9.]])]

In [72]:
np.vsplit(x,2)

[array([[8., 6., 6., 1., 3., 4., 7., 9., 2., 9., 0., 4.]]),
 array([[5., 4., 7., 7., 1., 3., 0., 9., 0., 2., 0., 9.]])]

## FANCY INDEXING AND INDEX TRICKS

In [44]:
q = np.arange(12)**2

In [45]:
i = np.array([1, 1, 5, 8, 10])

In [46]:
q[i]

array([  1,   1,  25,  64, 100])

In [69]:
j = np.arange(4).reshape(2,2)
print(j)

[[0 1]
 [2 3]]


In [48]:
q[j]

array([[0, 1],
       [4, 9]])

In [60]:
q = np.arange(12).reshape(3,4)
print(q)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [61]:
r = np.array([ [0,1], [1,2]])

In [62]:
s = np.array([[2,1],
            [3,3]])

In [63]:
q[r,s]                    ## r and s must be same

array([[ 2,  5],
       [ 7, 11]])

In [64]:
q[r, 2]

array([[ 2,  6],
       [ 6, 10]])

In [65]:
q[:,j]

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [66]:
t = np.arange(5)
print(t)

[0 1 2 3 4]


In [67]:
t[[0, 1, 3]] = 0
print(t)

[0 0 2 0 4]


In [68]:
t[[0, 1, 3]] = 1,2,3
print(t)

[1 2 2 3 4]


In [76]:
u = np.floor(10*np.random.random((4,3)))
v = np.ones(3).reshape(1,3)
print(u+v)

[[7. 9. 6.]
 [1. 7. 4.]
 [1. 7. 2.]
 [3. 2. 2.]]
