In [28]:
import numpy as np

### **OPERATIONS ON ndarray**

In [29]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
c = a+b
d = a-b
print(c, d)

[20 31 42 53] [20 29 38 47]


In [30]:
g = a*b
print(g)

[  0  30  80 150]


In [34]:
b*2

array([0, 2, 4, 6])

In [5]:
f = b**2
print(f)

[0 1 4 9]


In [6]:
np.sin(a)

array([ 0.91294525, -0.98803162,  0.74511316, -0.26237485])

*Matrix Multiplication*

In [7]:
a = np.arange(6).reshape(3,2)
b = np.arange(10, 70, 10).reshape(2,3)
a@b

array([[ 40,  50,  60],
       [140, 190, 240],
       [240, 330, 420]])

In [8]:
a.dot(b)

array([[ 40,  50,  60],
       [140, 190, 240],
       [240, 330, 420]])

 += , -= are used for inplace modification of array*

## UNARY OPERATIONS 

In [9]:
a = np.random.random((2,3))
print(a)

[[0.67515573 0.17722622 0.66248185]
 [0.36426415 0.76308345 0.02552134]]


In [10]:
a.sum()

2.6677327401730766

In [11]:
a.min()

0.025521340160468142

In [12]:
a.max()

0.7630834543230236

*By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However,
by specifying the axis parameter you can apply an operation along the specified axis of an array*

In [13]:
b = np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
b.sum(axis=0)     ## Sum of each column (0 for column)

array([18, 22, 26])

In [15]:
b.sum(axis=1)     ## Sum of each row (1 for row)

array([ 3, 12, 21, 30])

In [16]:
b.cumsum(axis=1)  ##  Cumulative sum of each row

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21],
       [ 9, 19, 30]])

## UNIVERSAL OPERATIONS
* Operates on each element of numpy array*

In [17]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04])

In [19]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

In [20]:
b = np.arange(-12, 0, 1)
b

array([-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [21]:
np.add(a,b)

array([-12, -10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8,  10])

In [22]:
np.subtract(a,b)

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

*Mean, Median, Mode, average, etc*

In [23]:
np.mean(a)

5.5

In [24]:
np.median(a)

5.5

In [25]:
np.std(a)

3.452052529534663

In [26]:
np.average(a)

5.5